//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public int UserId { get; set; }
        public int AlarmItem_Id { get; set; }
    
        public virtual AlarmItem AlarmItem { get; set; }
        public virtual User ResponsibleUser { get; set; }
    }
}
